In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

## Create & Read

### 1D Array

In [3]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(4,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

In [8]:
arr1.size

4

### 2D Array

In [10]:
arr2 = np.array([[1,4,5], [5,6,7]])
arr2

array([[1, 4, 5],
       [5, 6, 7]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 3)

In [13]:
arr2.dtype

dtype('int64')

In [14]:
arr2.size


6

### Create random array

In [16]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.87466648, 0.16789183, 0.66955839],
        [0.01685759, 0.92042326, 0.47820801]],

       [[0.5915775 , 0.90903972, 0.68639253],
        [0.86960422, 0.06537282, 0.8500325 ]],

       [[0.75351546, 0.00202968, 0.09331517],
        [0.30364977, 0.88723921, 0.43135289]]])

In [18]:
randomArr.dtype

dtype('float64')

In [24]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
zeros.ndim

3

In [28]:
full = np.full((3,2,3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [30]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Update & Delete

In [33]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [34]:
a1

array([[[0.33733224, 0.74994818],
        [0.441878  , 0.22522472],
        [0.69251474, 0.12529188]],

       [[0.62798713, 0.59750668],
        [0.55433894, 0.56214314],
        [0.80196367, 0.43170885]]])

In [35]:
a2

array([[[0.64998494, 0.4058497 ],
        [0.81087288, 0.24518158],
        [0.79875551, 0.39692107]],

       [[0.32326113, 0.76122224],
        [0.64728227, 0.85335308],
        [0.98413968, 0.87213736]]])

### Basic Math Operation

In [36]:
np.add(a1,a2)

array([[[0.98731718, 1.15579788],
        [1.25275088, 0.4704063 ],
        [1.49127025, 0.52221295]],

       [[0.95124826, 1.35872892],
        [1.20162121, 1.41549621],
        [1.78610334, 1.30384621]]])

In [37]:
np.subtract(a1,a2)

array([[[-0.31265269,  0.34409847],
        [-0.36899487, -0.01995686],
        [-0.10624076, -0.2716292 ]],

       [[ 0.304726  , -0.16371556],
        [-0.09294333, -0.29120994],
        [-0.18217601, -0.4404285 ]]])

In [39]:
np.divide(a1,a2)

array([[[0.51898471, 1.84784705],
        [0.54494116, 0.91860375],
        [0.86699214, 0.31565942]],

       [[1.94266205, 0.78493066],
        [0.85640989, 0.65874625],
        [0.81488805, 0.49500099]]])

In [40]:
np.multiply(a1,a2)

array([[[0.21926088, 0.30436624],
        [0.35830689, 0.05522095],
        [0.55314997, 0.04973099]],

       [[0.20300383, 0.45483537],
        [0.35881377, 0.47970657],
        [0.78924426, 0.37650942]]])

### Appending & Inserting

In [44]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
new_array = np.ones([3,2,3])
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [53]:
appd = np.append(zeros, new_array, axis=0)

In [54]:
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [49]:
appd.size

36

In [50]:
appd.ndim

3

### Insert

In [56]:
inserted_array = np.insert(zeros, 1, ones, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [57]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.16690789, 0.60542395, 0.9871037 ],
        [0.21993224, 0.5217503 , 0.71858545]],

       [[0.89688806, 0.86564281, 0.79487008],
        [0.5329993 , 0.84524665, 0.8327631 ]],

       [[0.20920031, 0.49724519, 0.99271917],
        [0.8864482 , 0.28974781, 0.48009281]]])

In [61]:
# delete teh array
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.21993224, 0.5217503 , 0.71858545]],

       [[0.5329993 , 0.84524665, 0.8327631 ]],

       [[0.8864482 , 0.28974781, 0.48009281]]])

In [62]:
np.save("new_array", arr5)

In [63]:
np.load("new_array.npy")

array([[[0.21993224, 0.5217503 , 0.71858545]],

       [[0.5329993 , 0.84524665, 0.8327631 ]],

       [[0.8864482 , 0.28974781, 0.48009281]]])